// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAszKGDXiWn-kRlgNzvGlRS4cdFS5OJiuY',
    appId: '1:796465793361:web:275bcae3f4a0dd4df6ab70',
    messagingSenderId: '796465793361',
    projectId: 'remindcircle-af485',
    authDomain: 'remindcircle-af485.firebaseapp.com',
    storageBucket: 'remindcircle-af485.firebasestorage.app',
    measurementId: 'G-BYDTRKXVPL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4FY6Qb4d1W_FU96tV2C9DhM_Tl0D108Y',
    appId: '1:796465793361:android:1849d400fa3dba13f6ab70',
    messagingSenderId: '796465793361',
    projectId: 'remindcircle-af485',
    storageBucket: 'remindcircle-af485.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj0rpKCYuZBtm0dq7pWL9VW1IjDGpds0M',
    appId: '1:796465793361:ios:d88f077cde6ac283f6ab70',
    messagingSenderId: '796465793361',
    projectId: 'remindcircle-af485',
    storageBucket: 'remindcircle-af485.firebasestorage.app',
    iosBundleId: 'com.example.remindCircle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj0rpKCYuZBtm0dq7pWL9VW1IjDGpds0M',
    appId: '1:796465793361:ios:d88f077cde6ac283f6ab70',
    messagingSenderId: '796465793361',
    projectId: 'remindcircle-af485',
    storageBucket: 'remindcircle-af485.firebasestorage.app',
    iosBundleId: 'com.example.remindCircle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAszKGDXiWn-kRlgNzvGlRS4cdFS5OJiuY',
    appId: '1:796465793361:web:eede1fe3f06aaf60f6ab70',
    messagingSenderId: '796465793361',
    projectId: 'remindcircle-af485',
    authDomain: 'remindcircle-af485.firebaseapp.com',
    storageBucket: 'remindcircle-af485.firebasestorage.app',
    measurementId: 'G-PTDGHZ2W6F',
  );
}
